server:
  port: 5500
 
spring:
  application:
    name: prepper-api

  datasource:
    driverClassName: org.postgresql.Driver
    initialization-mode: NEVER
    password: ${DB_PASSWORD}
    url: jdbc:postgresql://${DB_URL}:5432/postgres
    username: ${DB_USERNAME}
    
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_schema: ${DB_SCHEMA}
    show-sql: false
    #http://ec2-18-225-37-190.us-east-2.compute.amazonaws.com:5500/api/swagger-ui.html
    
